services:
  farmaciaaiangular:
    image: farmaciaaiangular
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5001:5000
    networks:
      - pgnet

networks:
  pgnet:
    external: true
